trigger:
- main

pool:
  vmImage: 'windows-latest'

jobs:
- job: Deploy
  displayName: 'Deploy Azure Function'
  steps:

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration Release'

  - task: DotNetCoreCLI@2
    displayName: 'Publish'
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration Release --output $(build.artifactstagingdirectory)/output'
      zipAfterPublish: true

  - task: AzureRmWebAppDeployment@4
    displayName: 'Deploy to Azure Functions'
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'YourAzureSubscription'
      appType: 'functionApp'
      WebAppName: 'YourAzureFunctionAppName'
      packageForLinux: '$(build.artifactstagingdirectory)/output/*.zip'

  - task: AzureCLI@2
    displayName: 'Configure Application Settings'
    inputs:
      azureSubscription: 'YourAzureSubscription'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az functionapp config appsettings set --name YourAzureFunctionAppName --resource-group YourResourceGroupName --settings MySetting1=Value1 MySetting2=Value2

  - task: AzureCLI@2
    displayName: 'Configure Service Bus Connection String'
    inputs:
      azureSubscription: 'YourAzureSubscription'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az functionapp config appsettings set --name YourAzureFunctionAppName --resource-group YourResourceGroupName --settings ServiceBusConnectionString="YourServiceBusConnectionString"

# Additional tasks or steps can be added as needed.
