# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
steps:
    - task: DotNetCoreCLI@2
      displayName: 'Publish SalesOrder'
      condition: and(succeeded() , eq(variables['BuildSalesOrder'], 'true'))
      inputs:
        command: 'publish'
        publishWebProjects: false
        modifyOutputPath: false
        zipAfterPublish: false
        arguments: '--configuration Release --output publish_output_SalesOrder'
        projects: '$(System.DefaultWorkingDirectory)/ServiceBusIntegration/ServiceBusIntegration/ServiceBusTrigger.csproj'
    - task: ArchiveFiles@2
      condition: and(succeeded() , eq(variables['BuildSalesOrder'], 'true'))
      displayName: "Archive SalesOrder"
      inputs:
        rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output_SalesOrder"
        includeRootFolder: false
        archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId)SalesOrder.zip"
    - task: PublishBuildArtifacts@1
      displayName: SalesOrder
      condition: and(succeeded() , eq(variables['BuildSalesOrder'], 'true'))
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId)SalesOrder.zip'
        artifactName: 'drop_salesOrder'